### ISSUE TITLE
Plugin fails on Windows

### ISSUE THREAD

**Issue by chrisphe** [alexec/docker-java-orchestration#38]
On Windows, when doing Runtime.exec(), the Stderr and Stdout streams need to be drained before doing waitFor. This approach should work across platforms (as per exec() documentation).

This patch allows the plugin to work on Windows with Boot2Docker.

**Comment by chrisphe** [comment]
Patch https://github.com/alexec/docker-java-orchestration/pull/37

**Comment by chrisphe** [comment]
https://github.com/docker-java/docker-java/issues/252

**Comment by chrisphe** [comment]
The above two PRs are to address this issue. Thanks Chris

**Comment by chrisphe** [comment]
Fixes have been applied - thanks.

**Comment by alexec** [comment]
Will need to wait until docker-java is released.

**Comment by chrisphe** [comment]
For information, looks like the new release of docker-java has been made. Thanks, Rgds
