### ISSUE TITLE
Not compatible with docker-java 2.x

### ISSUE THREAD

**Issue by marcust** [alexec/docker-java-orchestration#49]
Currently one can't use docker-java-orchestration together with current versions of docker-java. Unfortunately those are needed to use docker > 1.6.x.

I might find some time next week to attempt a port, just wanted to make sure we do not double the effort.

**Comment by alexec** [comment]
I'm a busy ATM, so I'd love it if you could port it for me!

**Comment by alexec** [comment]
@marcust  -- I have one last issue, this build is failing:

https://circleci.com/gh/alexec/docker-maven-plugin/282

This is related to authentication. I'll try and look at next weekend. 

Thank you for all your work.

**Comment by marcust** [comment]
Yes, that is due to circle ci using docker 1.6.2

The issue docker-java/docker-java/issues/288 explains the changes. I didn't know that they fixed it as a breaking change as well in docker-java :(

**Comment by alexec** [comment]
Hmm. I wonder what is best to do? Wait for CircleCI to fix it, or to set version or get docker-java backwards compatible?

**Comment by marcust** [comment]
Well, what the docker-py people did was to make it dependent on the version of the API (docker-java/docker-java/issues/288), but I don't know if that is equally possible with docker-java. I will have a look tomorrow and see if there is something equally easy in docker-java in order to achieve backward compatibility.

**Comment by marcust** [comment]
This will work as soon as docker-java releases a new version and we can bump the dependency version.

**Comment by marcust** [comment]
Fix is in the version 2.1.2 of docker-java, PR for orchestration has been merged, so if this is released we finally solved the issue.
