### ISSUE TITLE
Change in package/add behaviour in 2.11.4

### ISSUE THREAD

**Issue by alexec** [alexec/docker-java-orchestration#71]
Prior to 2.11.4, the following configuration would add a directory to the build

~~~yml
packging:
  add:
  - myDir
~~~

Would be copied into `target/docker/app/myDir`. Now it is copied to `target/docker/app`. I can see this being useful, but I would like to be able to do both. 

# Option 1

Reinstate behaviour.

# Option 2

~~~yml
packging:
  add:
  # glob match
  - myDir/*
~~~

# Option 3

~~~yml
packging:
  add:
  # target directory
  - myDir myDir
~~~

# Option 4

~~~yml
packging:
  add:
  # trailing slash
  - myDir/
~~~

@marcust  - thoughts?

**Comment by marcust** [comment]
@alexec Was that a side effect of my changes to the FileOrchestrator? That was not intended.  

Just first thoughts:
# Option 1:
I would do that

# Option 2: 
That would actually be my first though for the current behaviour, take those files and copy them flat to the target directory.

# Option 3 & 4
IMHO to obscure

**Comment by marcust** [comment]
I actually didn't implement Option 2 just yet, because I don't really have a usecase, but that should be easy now that we have test coverage there.
