### ISSUE TITLE
findContainer not finding an existing container

### ISSUE THREAD

**Issue by thomasesh** [alexec/docker-java-orchestration#74]
I am trying to start a container and it is failing because the findContainer method is not finding the container even though the container exists.   Below is the partial output of:
            mvn -X -e docker:start

Is shows that the iapserver container exists but the findContainer method is unable to find it.

Am I doing something incorrect?

Tom

[DEBUG] Executing request GET /v1.21/containers/json?all=1&size=0 HTTP/1.1
[DEBUG] Target auth state: UNCHALLENGED
[DEBUG] Proxy auth state: UNCHALLENGED
[DEBUG] http-outgoing-1 >> GET /v1.21/containers/json?all=1&size=0 HTTP/1.1
[DEBUG] http-outgoing-1 >> Accept: application/json
[DEBUG] http-outgoing-1 >> User-Agent: Jersey/2.11 (Apache HttpClient 4.3.1)
[DEBUG] http-outgoing-1 >> Host: localhost:80
[DEBUG] http-outgoing-1 >> Connection: Keep-Alive
[DEBUG] http-outgoing-1 >> Accept-Encoding: gzip,deflate
[DEBUG] http-outgoing-1 >> "GET /v1.21/containers/json?all=1&size=0 HTTP/1.1[\r][\n]"
[DEBUG] http-outgoing-1 >> "Accept: application/json[\r][\n]"
[DEBUG] http-outgoing-1 >> "User-Agent: Jersey/2.11 (Apache HttpClient 4.3.1)[\r][\n]"
[DEBUG] http-outgoing-1 >> "Host: localhost:80[\r][\n]"
[DEBUG] http-outgoing-1 >> "Connection: Keep-Alive[\r][\n]"
[DEBUG] http-outgoing-1 >> "Accept-Encoding: gzip,deflate[\r][\n]"
[DEBUG] http-outgoing-1 >> "[\r][\n]"
[DEBUG] http-outgoing-1 << "HTTP/1.1 200 OK[\r][\n]"
[DEBUG] http-outgoing-1 << "Content-Type: application/json[\r][\n]"
[DEBUG] http-outgoing-1 << "Server: Docker/1.9.1 (linux)[\r][\n]"
[DEBUG] http-outgoing-1 << "Date: Mon, 11 Jan 2016 14:11:16 GMT[\r][\n]"
[DEBUG] http-outgoing-1 << "Transfer-Encoding: chunked[\r][\n]"
[DEBUG] http-outgoing-1 << "[\r][\n]"
[DEBUG] http-outgoing-1 << "886[\r][\n]"
[DEBUG] http-outgoing-1 << "[{"Id":"1d4c713d94b2403d23858812cf397f03db49fe389be70c05b1e42c31c28f2333","Names":["/iapserver"],"Image":"9b81c030fbe5b657870931c9745a7d9ef28b762c7d20c9a8b9253c001e097a76","ImageID":"9b81c030fbe5b657870931c9745a7d9ef28b762c7d20c9a8b9253c001e097a76","Command":"/bin/sh -c 'java   -Dcom.sun.management.jmxremote.ssl=false   -Dcom.sun.management.jmxremote.authenticate=false   -Diap.tcp.port=12100   -Dcom.sun.management.jmxremote.port=12101   -Dlogback.configurationFile=/opt/acme/iap/server/logback-server.xml   -jar /opt/acme/iap/server/acme-iap-server-1.0.0-SNAPSHOT-onejar.jar   file:///opt/acme/iap/server/server-config.xml'","Created":1452521474,"Ports":[{"IP":"0.0.0.0","PrivatePort":12101,"PublicPort":12101,"Type":"tcp"},{"IP":"0.0.0.0","PrivatePort":12100,"PublicPort":12100,"Type":"tcp"}],"Labels":{"build-date":"2015-12-23","license":"GPLv2","name":"CentOS Base Image","vendor":"CentOS"},"Status":"Up 1 seconds","HostConfig":{"NetworkMode":"default"}},{"Id":"d6097d62bfe734172955bc1cf3dd9e17e6f8198dbedd451fb58b1549752cf211","Names":["/big_bell"],"Image":"registry.platform.cas.org/org.cas.acme/build-environment","ImageID":"36d2a2a3bd7f57f9bad2ab19b09bec7a47fda6f00ae4adaeeb00d6c3ec4f3d0a","Command":"mvn -X -e docker:start","Created":1452521471,"Ports":[],"Labels":{},"Status":"Up 4 seconds","HostConfig":{"NetworkMode":"host"}},{"Id":"2ea65bc5fd5f3c763b144dd553a5fe2da30aa5d92ae30b0b7f2388a1f3dc580e","Names":["/iap-server"],"Image":"2013c9d65a038de4698ce3727beec8191f5c4087823005f6841feb718af2f0d6","ImageID":"2013c9d65a038de4698ce3727beec8191f5c4087823005f6841feb718af2f0d6","Command":"/bin/sh -c 'java   -Dcom.sun.management.jmxremote.ssl=false   -Dcom.sun.management.jmxremote.authenticate=false   -Diap.tcp.port=12100   -Dcom.sun.management.jmxremote.port=12101   -Dlogback.configurationFile=/opt/acme/iap/server/logback-server.xml   -jar /opt/acme/iap/server/acme-iap-server-1.0.0-SNAPSHOT-onejar.jar   file:///opt/acme/iap/server/server-config.xml'","Created":1452519123,"Ports":[],"Labels":{"build-date":"2015-12-23","license":"GPLv2","name":"CentOS Base Image","vendor":"CentOS"},"Status":"Exited (143) 14 minutes ago","HostConfig":{"NetworkMode":"default"}}][\n]"
[DEBUG] http-outgoing-1 << "[\r][\n]"
[DEBUG] http-outgoing-1 << "0[\r][\n]"
[DEBUG] http-outgoing-1 << "[\r][\n]"
[DEBUG] http-outgoing-1 << HTTP/1.1 200 OK
[DEBUG] http-outgoing-1 << Content-Type: application/json
[DEBUG] http-outgoing-1 << Server: Docker/1.9.1 (linux)
[DEBUG] http-outgoing-1 << Date: Mon, 11 Jan 2016 14:11:16 GMT
[DEBUG] http-outgoing-1 << Transfer-Encoding: chunked
[DEBUG] Connection can be kept alive indefinitely
[DEBUG] 14 * Client response received on thread main
14 < 200
14 < Content-Length: -1
14 < Content-Type: application/json
14 < Date: Mon, 11 Jan 2016 14:11:16 GMT
14 < Server: Docker/1.9.1 (linux)
14 < Transfer-Encoding: chunked
[{"Id":"1d4c713d94b2403d23858812cf397f03db49fe389be70c05b1e42c31c28f2333","Names":["/iapserver"],"Image":"9b81c030fbe5b657870931c9745a7d9ef28b762c7d20c9a8b9253c001e097a76","ImageID":"9b81c030fbe5b657870931c9745a7d9ef28b762c7d20c9a8b9253c001e097a76","Command":"/bin/sh -c 'java   -Dcom.sun.management.jmxremote.ssl=false   -Dcom.sun.management.jmxremote.authenticate=false   -Diap.tcp.port=12100   -Dcom.sun.management.jmxremote.port=12101   -Dlogback.configurationFile=/opt/acme/iap/server/logback-server.xml   -jar /opt/acme/iap/server/acme-iap-server-1.0.0-SNAPSHOT-onejar.jar   file:///opt/acme/iap/server/server-config.xml'","Created":1452521474,"Ports":[{"IP":"0.0.0.0","PrivatePort":12101,"PublicPort":12101,"Type":"tcp"},{"IP":"0.0.0.0","PrivatePort":12100,"PublicPort":12100,"Type":"tcp"}],"Labels":{"build-date":"2015-12-23","license":"GPLv2","name":"CentOS Base Image","vendor":"CentOS"},"Status":"Up 1 seconds","HostConfig":{"NetworkMode":"default"}},{"Id":"d6097d62bfe734172955bc1cf3dd9e17e6f8198dbedd451fb58b1549752cf211","Names":["/big_bell"],"Image":"registry.platform.cas.org/org.cas.acme/build-environment","ImageID":"36d2a2a3bd7f57f9bad2ab19b09bec7a47fda6f00ae4adaeeb00d6c3ec4f3d0a","Command":"mvn -X -e docker:start","Created":1452521471,"Ports":[],"Labels":{},"Status":"Up 4 seconds","HostConfig":{"NetworkMode":"host"}},{"Id":"2ea65bc5fd5f3c763b144dd553a5fe2da30aa5d92ae30b0b7f2388a1f3dc580e","Names":["/iap-server"],"Image":"2013c9d65a038de4698ce3727beec8191f5c4087823005f6841feb718af2f0d6","ImageID":"2013c9d65a038de4698ce3727beec8191f5c4087823005f6841feb718af2f0d6","Command":"/bin/sh -c 'java   -Dcom.sun.management.jmxremote.ssl=false   -Dcom.sun.management.jmxremote.authenticate=false   -Diap.tcp.port=12100   -Dcom.sun.management.jmxremote.port=12101   -Dlogback.configurationFile=/opt/acme/iap/server/logback-server.xml   -jar /opt/acme/iap/server/acme-iap-server-1.0.0-SNAPSHOT-onejar.jar   file:///opt/acme/iap/server/server-config.xml'","Created":1452519123,"Ports":[],"Labels":{"build-date":"2015-12-23","license":"GPLv2","name":"CentOS Base Image","vendor":"CentOS"},"Status":"Exited (143) 14 minutes ago","HostConfig":{"NetworkMode":"default"}}]

[DEBUG] Connection [id: 1][route: {}->unix://localhost:80] can be kept alive indefinitely
[DEBUG] Connection released: [id: 1][route: {}->unix://localhost:80][total kept alive: 1; route allocated: 1 of 2; total allocated: 1 of 20]
[WARNING] Can not find container iapserver, not waiting

**Comment by alexec** [comment]
No response. Assuming fixed, or don't care.
