### ISSUE TITLE
Windows Absolute Path for createNewContainer

### ISSUE THREAD

**Issue by csarthou** [alexec/docker-java-orchestration#77]
Hello,

I'm using your plugin docker-maven-plugin , and all is fine for my executions from my server Jenkins.

Thank you for all, it's perfect for my use!

But there is a problem when I want to execute the maven goal "start" from my Windows developpement environment.

During createNewContainer, and the volume declaration, there is a log message : 

[INFO]  - volumes /var/docker/testserver/S01 <- **C:**\var\docker\testserver\S01

This is my volume configuration in conf.yml : 

volumes:
  /var/docker/testserver/S01: /var/docker/testserver/S01

But my Docker server is a Linux server... And I receive : 

[DEBUG] http-outgoing-5 << "HTTP/1.1 500 Internal Server Error[\r][\n]"
[DEBUG] http-outgoing-5 << "Content-Type: text/plain; charset=utf-8[\r][\n]"
[DEBUG] http-outgoing-5 << "Server: Docker/1.9.1 (linux)[\r][\n]"
[DEBUG] http-outgoing-5 << "Date: Mon, 01 Feb 2016 16:21:11 GMT[\r][\n]"
[DEBUG] http-outgoing-5 << "Content-Length: 87[\r][\n]"
[DEBUG] http-outgoing-5 << "[\r][\n]"
[DEBUG] http-outgoing-5 << "Invalid volume specification: C:\var\docker\testserver\S01:/var/docker/testserver/S01:rw[\n]"
[DEBUG] http-outgoing-5 << HTTP/1.1 500 Internal Server Error
[DEBUG] http-outgoing-5 << Content-Type: text/plain; charset=utf-8
[DEBUG] http-outgoing-5 << Server: Docker/1.9.1 (linux)
[DEBUG] http-outgoing-5 << Date: Mon, 01 Feb 2016 16:21:11 GMT
[DEBUG] http-outgoing-5 << Content-Length: 87

I think it's because the command "file.getAbsolutePath()" in createNewContainer is done on my Windows developpement environment, for Linux use, but I'm not sure.

Thank you for your job and your help.

Chris

**Comment by alexec** [comment]
Hi,

I have pushed fix to the latest snapshot version. Do you think you could please check it works for you?

Alex

**Comment by csarthou** [comment]
Hi,

I have downloaded the latest snapshot versions of docker-maven-plugin and docker-java-orchestration

I have configured my plugin like this :  
				<groupId>com.alexecollins.docker</groupId>
				<artifactId>docker-maven-plugin</artifactId>
				<version>2.11.10-SNAPSHOT</version>

And all is OK for me on my Windows environment.

Thank you one more time for your job.


Chris

**Comment by alexec** [comment]
Fixed.
