### ISSUE TITLE
Can we make forcing when deleting an option?

### ISSUE THREAD

**Issue by marcust** [alexec/docker-java-orchestration#81]
I just realized that you reintegrated the force option for image deletes again. I think I removed it last year ;)

The thing is that in my usecase we quite often don't actually do something in the build step, just having a FROM line, and this creates an Image with the same Id as the original image. If it is now force deleted then it removes the base image as well and that is not what I want, because then I have to redownload it again. 

Can we make this an option that defaults to false, meaning don't force?

**Comment by alexec** [comment]
Sure. It was meant to be a bug fix, bug I guess it needs to be configurable and false by default (for backwards compatibility).

**Comment by alexec** [comment]
This is done I think.
