### ISSUE TITLE
Port to docker-java 3.0.0

### ISSUE THREAD

**Issue by marcust** [alexec/docker-java-orchestration#84]
I've the code changes ready for using the latest release of docker-java. The thing is that apparently the whole auth flow has changed in 3.0 (you give only the path to your .dockercfg and not the full filename anymore) and `master` already has additional changes to the authentication code. 

I tested the version and it works, but as there will be additional changes I might not roll-out a 3.0 based version just yet in order to have the work with the authentication changes just once.

What do you think?

**Comment by alexec** [comment]
Hi Marcus,

It is better to do painful things first eh? I say let do it.

Alex

**Comment by alexec** [comment]
This is done.
